### ISSUE TITLE
Powerlink3, GSM module questions

### ISSUE THREAD

**Issue by brownad** [michaelmcneela/homebridge-visonic-powerlink2#1]
Hi,

Great work brining this together, is powerlink3 supported (powermaster)?  Would you have any smart ideas for GSM module, is there a pass through to the web front end?

Thanks

**Comment by michaelmcneela** [comment]
Thanks! I believe the PowerLink3 is _very_ different to the 2; that it seemingly doesn't serve its own web server / API on the local network.

From the "PowerMaster-10/30 Installer and Quick User Guide", page 85: 

> Note: PowerLink3 IP Communicator does not include viewing [by] cameras or control of options via a web interface.

[This project](https://github.com/barcar/visonic_control), however, appears to enable control of the PowerLink3 _via an external server_ (running Visonic PowerManage?)– the HTTP calls it uses could be used to create a separate PowerLink3 plugin…

**Comment by brownad** [comment]
Yeah powermanage is a third party that runs kit to monitor visonic alarms.  One way or another the GSM or powerlink3 connect in via web calls.  I’ll check the project thanks 😎
